### ISSUE TITLE
[SDK] Improve reconnection logic (sync subtensor)

### ISSUE THREAD

**Issue by basfroman** [camfairchild/bittensor#2444]

**Comment by basfroman** [comment]
PR https://github.com/opentensor/bittensor/pull/2442

**Comment by thewhaleking** [comment]
Issue regarding reconnection. Eclipse Vortex in Discord pointed out that he was randomly having validators freeze up. Total freeze. He narrowed this down to this call in `bittensor.core.extrinsics.utils`:
```py
response = substrate.submit_extrinsic(
    extrinsic,
    wait_for_inclusion=wait_for_inclusion,
    wait_for_finalization=wait_for_finalization,
)
```

Running v8.3.1, with `wait_for_inclusion=True`

I believe what is happening is that a subscription handler is created due to submitting the extrinsic with `wait_for_inclusion=True`, and then there is a connection interrupt. We are reconnecting, but due to how websockets work, our websocket connection will never receive the result of the subscription indicating success/failure. Thus, it is stuck in an infinite loop of polling.

**Comment by thewhaleking** [comment]
Relates to #2454 and #2448
